name: Pre Uptime

on:
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch:

jobs:
  healthcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install yq
        run: |
          sudo wget -O /usr/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/bin/yq
      - name: Precheck endpoints
        run: |
          echo "Read endpoints from .upptimerc.yml..."
          URLS=$(yq -r '.sites[].url' .upptimerc.yml)

          echo "Load secrets..."
          secrets_json="$SECRETS_CONTEXT"
          
          for url in $URLS; do
            # Replace secret
            if [[ "$url" =~ ^\$([A-Z0-9_]+)$ ]]; then
              secret_name="${BASH_REMATCH[1]}"
              expanded_url=$(echo "$secrets_json" | jq -r --arg key "$secret_name" '.[$key]')
            else
              expanded_url="$url"
            fi

            echo "Call $expanded_url ..."
            if curl -o /dev/null -s -w "%{http_code}" --max-time 5 "$expanded_url" >/dev/null; then
              echo "✅ $expanded_url"
            else
              echo "❌ $expanded_url"
            fi
          done
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
